package com.example.demo.mybatis.dto;

import java.util.Date;

public class History {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.id
     *
     * @mbg.generated Thu May 25 17:43:03 JST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.value
     *
     * @mbg.generated Thu May 25 17:43:03 JST 2017
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.regist_datetime
     *
     * @mbg.generated Thu May 25 17:43:03 JST 2017
     */
    private Date registDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.id
     *
     * @return the value of history.id
     *
     * @mbg.generated Thu May 25 17:43:03 JST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.id
     *
     * @param id the value for history.id
     *
     * @mbg.generated Thu May 25 17:43:03 JST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.value
     *
     * @return the value of history.value
     *
     * @mbg.generated Thu May 25 17:43:03 JST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.value
     *
     * @param value the value for history.value
     *
     * @mbg.generated Thu May 25 17:43:03 JST 2017
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.regist_datetime
     *
     * @return the value of history.regist_datetime
     *
     * @mbg.generated Thu May 25 17:43:03 JST 2017
     */
    public Date getRegistDatetime() {
        return registDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.regist_datetime
     *
     * @param registDatetime the value for history.regist_datetime
     *
     * @mbg.generated Thu May 25 17:43:03 JST 2017
     */
    public void setRegistDatetime(Date registDatetime) {
        this.registDatetime = registDatetime;
    }
}